Sport.Web.Configuration/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Sport.Configuration;
using Sport.Configuration.Models;

namespace Sport.Web.Configuration.Controllers
{
    public class TeamController : Controller
    {
        private readonly ConfigurationContext _db = new ConfigurationContext();

        // GET: /Team/
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.LeagueSortParm = sortOrder == "league" ? "league_desc" : "league";
            ViewBag.ZoneSortParm = sortOrder == "zone" ? "zone_desc" : "zone";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var teams = from s in _db.Teams
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                teams = teams.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper()) ||
                    s.Zone.Name.ToUpper().Equals(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    teams = teams.OrderByDescending(s => s.Name);
                    break;
                case "zone_desc":
                    teams = teams.OrderByDescending(s => s.Zone.Name);
                    break;
                case "zone":
                    teams = teams.OrderBy(t => t.Zone.Name);
                    break;
                case "league_desc":
                    teams = teams.OrderByDescending(s => s.League.Name);
                    break;
                case "league":
                    teams = teams.OrderBy(s => s.League.Name);
                    break;
                default:  // Name ascending 
                    teams = teams.OrderBy(s => s.Name);
                    break;
            }

            const int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(teams.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Team/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = _db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // GET: /Team/Create
        public ActionResult Create()
        {
            ViewBag.LeagueId = new SelectList(_db.Leagues, "Id", "Name");
            ViewBag.ZoneId = new SelectList(_db.Zones, "Id", "Name");
            return View();
        }

        // POST: /Team/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,IsActive,Chemistry,OverallRating,LeagueId,MigrationId,ZoneId")] Team team)
        {
            if (ModelState.IsValid)
            {
                team.Id = Guid.NewGuid();
                _db.Teams.Add(team);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeagueId = new SelectList(_db.Leagues, "Id", "Name", team.LeagueId);
            ViewBag.ZoneId = new SelectList(_db.Zones, "Id", "Name", team.ZoneId);
            return View(team);
        }

        // GET: /Team/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = _db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeagueId = new SelectList(_db.Leagues, "Id", "Name", team.LeagueId);
            ViewBag.ZoneId = new SelectList(_db.Zones, "Id", "Name", team.ZoneId);
            return View(team);
        }

        // POST: /Team/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,IsActive,Chemistry,OverallRating,LeagueId,MigrationId,ZoneId")] Team team)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(team).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeagueId = new SelectList(_db.Leagues, "Id", "Name", team.LeagueId);
            ViewBag.ZoneId = new SelectList(_db.Zones, "Id", "Name", team.ZoneId);
            return View(team);
        }

        // GET: /Team/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = _db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: /Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Team team = _db.Teams.Find(id);
            _db.Teams.Remove(team);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sport.Web.Configuration/Views/Team/Create.cshtml
@model Sport.Configuration.Models.Team

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chemistry, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chemistry)
                @Html.ValidationMessageFor(model => model.Chemistry)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverallRating, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OverallRating)
                @Html.ValidationMessageFor(model => model.OverallRating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeagueId, "LeagueId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LeagueId", String.Empty)
                @Html.ValidationMessageFor(model => model.LeagueId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MigrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MigrationId)
                @Html.ValidationMessageFor(model => model.MigrationId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneId, "ZoneId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZoneId", String.Empty)
                @Html.ValidationMessageFor(model => model.ZoneId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sport.Web.Configuration/Views/Team/Delete.cshtml
@model Sport.Configuration.Models.Team

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.League.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.League.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zone.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zone.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chemistry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chemistry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OverallRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OverallRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MigrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MigrationId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sport.Web.Configuration/Views/Team/Details.cshtml
@model Sport.Configuration.Models.Team

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Team</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.League.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.League.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zone.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zone.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chemistry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chemistry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OverallRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OverallRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MigrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MigrationId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sport.Web.Configuration/Views/Team/Edit.cshtml
@model Sport.Configuration.Models.Team

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chemistry, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chemistry)
                @Html.ValidationMessageFor(model => model.Chemistry)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverallRating, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OverallRating)
                @Html.ValidationMessageFor(model => model.OverallRating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeagueId, "LeagueId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LeagueId", String.Empty)
                @Html.ValidationMessageFor(model => model.LeagueId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MigrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MigrationId)
                @Html.ValidationMessageFor(model => model.MigrationId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneId, "ZoneId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZoneId", String.Empty)
                @Html.ValidationMessageFor(model => model.ZoneId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sport.Web.Configuration/Views/Team/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Sport.Configuration.Models.Team>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Team", FormMethod.Get))
{
    <p>
        Find by name or zone: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("League", "Index", new { sortOrder = ViewBag.LeagueSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Zone", "Index", new { sortOrder = ViewBag.ZoneSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Active
        </th>
        <th>
            Chemistry
        </th>
        <th>
            OverallRating
        </th>
        <th>
            Migration Id
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.League.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zone.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chemistry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OverallRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MigrationId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

</table>

Total on page @Model.Count

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))