Sport.Web.ResultTracking/Controllers/ChampController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sport.Domain.Models;
using Sport.Domain.UoW;

namespace Sport.Web.ResultTracking.Controllers
{
    public class ChampController : Controller
    {
        private ISportUnitOfWork _sportUnitOfWork;
        private SportContext db = new SportContext();
        //private ISportUnitOfWork context = new SportUnitOfWork();
        
        public ChampController(ISportUnitOfWork sportUnitOfWork)
        {
            _sportUnitOfWork = sportUnitOfWork;
        }

        // GET: /Champ/
        public ActionResult Index(string champSeasonId)
        {
            var seasonId = new Guid(champSeasonId);
            var champs = _sportUnitOfWork.Champs.WithFixturesAndTeams().Where(x => x.ChampSeasonId == seasonId).ToList().OrderBy(x => x.Start);
            return View(champs.ToList());
        }

        // GET: /Champ/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Champ champ = db.Champs.Find(id);
            if (champ == null)
            {
                return HttpNotFound();
            }
            return View(champ);
        }

        // GET: /Champ/Create
        public ActionResult Create()
        {
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name");
            ViewBag.ZoneId = new SelectList(db.Zones, "Id", "Name");
            return View();
        }

        // POST: /Champ/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,ChampSeasonId,MigrationId,ZoneId,YellowsToMissNextMatch")] Champ champ)
        {
            if (ModelState.IsValid)
            {
                champ.Id = Guid.NewGuid();
                db.Champs.Add(champ);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champ.ChampSeasonId);
            ViewBag.ZoneId = new SelectList(db.Zones, "Id", "Name", champ.ZoneId);
            return View(champ);
        }

        // GET: /Champ/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Champ champ = db.Champs.Find(id);
            if (champ == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champ.ChampSeasonId);
            ViewBag.ZoneId = new SelectList(db.Zones, "Id", "Name", champ.ZoneId);
            return View(champ);
        }

        // POST: /Champ/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,ChampSeasonId,MigrationId,ZoneId,YellowsToMissNextMatch")] Champ champ)
        {
            if (ModelState.IsValid)
            {
                db.Entry(champ).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champ.ChampSeasonId);
            ViewBag.ZoneId = new SelectList(db.Zones, "Id", "Name", champ.ZoneId);
            return View(champ);
        }

        // GET: /Champ/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Champ champ = db.Champs.Find(id);
            if (champ == null)
            {
                return HttpNotFound();
            }
            return View(champ);
        }

        // POST: /Champ/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Champ champ = db.Champs.Find(id);
            db.Champs.Remove(champ);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sport.Web.ResultTracking/Controllers/ChampSeasonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sport.Domain.Models;

namespace Sport.Web.ResultTracking.Controllers
{
    public class ChampSeasonController : Controller
    {
        private SportContext db = new SportContext();

        // GET: /ChampSeason/
        public ActionResult Index()
        {
            var champseasons = db.ChampSeasons.Include(c => c.ChampType).Include(c => c.Parent);
            return View(champseasons.ToList());
        }

        // GET: /ChampSeason/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChampSeason champseason = db.ChampSeasons.Find(id);
            if (champseason == null)
            {
                return HttpNotFound();
            }
            return View(champseason);
        }

        // GET: /ChampSeason/Create
        public ActionResult Create()
        {
            ViewBag.ChampTypeId = new SelectList(db.ChampTypes, "Id", "Name");
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name");
            return View();
        }

        // POST: /ChampSeason/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Start,End,ChampTypeId,ChampSeasonId,MigrationId")] ChampSeason champseason)
        {
            if (ModelState.IsValid)
            {
                champseason.Id = Guid.NewGuid();
                db.ChampSeasons.Add(champseason);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ChampTypeId = new SelectList(db.ChampTypes, "Id", "Name", champseason.ChampTypeId);
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champseason.ChampSeasonId);
            return View(champseason);
        }

        // GET: /ChampSeason/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChampSeason champseason = db.ChampSeasons.Find(id);
            if (champseason == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChampTypeId = new SelectList(db.ChampTypes, "Id", "Name", champseason.ChampTypeId);
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champseason.ChampSeasonId);
            return View(champseason);
        }

        // POST: /ChampSeason/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Start,End,ChampTypeId,ChampSeasonId,MigrationId")] ChampSeason champseason)
        {
            if (ModelState.IsValid)
            {
                db.Entry(champseason).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChampTypeId = new SelectList(db.ChampTypes, "Id", "Name", champseason.ChampTypeId);
            ViewBag.ChampSeasonId = new SelectList(db.ChampSeasons, "Id", "Name", champseason.ChampSeasonId);
            return View(champseason);
        }

        // GET: /ChampSeason/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChampSeason champseason = db.ChampSeasons.Find(id);
            if (champseason == null)
            {
                return HttpNotFound();
            }
            return View(champseason);
        }

        // POST: /ChampSeason/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ChampSeason champseason = db.ChampSeasons.Find(id);
            db.ChampSeasons.Remove(champseason);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sport.Web.ResultTracking/Views/ChampSeason/Create.cshtml
@model Sport.Domain.Models.ChampSeason

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChampSeason</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start)
                @Html.ValidationMessageFor(model => model.Start)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End)
                @Html.ValidationMessageFor(model => model.End)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChampTypeId, "ChampTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChampTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.ChampTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChampSeasonId, "ChampSeasonId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChampSeasonId", String.Empty)
                @Html.ValidationMessageFor(model => model.ChampSeasonId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MigrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MigrationId)
                @Html.ValidationMessageFor(model => model.MigrationId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sport.Web.ResultTracking/Views/ChampSeason/Delete.cshtml
@model Sport.Domain.Models.ChampSeason

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChampSeason</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChampType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChampType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MigrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MigrationId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sport.Web.ResultTracking/Views/ChampSeason/Details.cshtml
@model Sport.Domain.Models.ChampSeason

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ChampSeason</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChampType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChampType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MigrationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MigrationId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sport.Web.ResultTracking/Views/ChampSeason/Edit.cshtml
@model Sport.Domain.Models.ChampSeason

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChampSeason</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start)
                @Html.ValidationMessageFor(model => model.Start)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End)
                @Html.ValidationMessageFor(model => model.End)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChampTypeId, "ChampTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChampTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.ChampTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChampSeasonId, "ChampSeasonId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChampSeasonId", String.Empty)
                @Html.ValidationMessageFor(model => model.ChampSeasonId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MigrationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MigrationId)
                @Html.ValidationMessageFor(model => model.MigrationId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sport.Web.ResultTracking/Views/ChampSeason/Index.cshtml
@model IEnumerable<Sport.Domain.Models.ChampSeason>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ChampType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Start)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.End)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MigrationId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ChampType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Parent.Name)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Name)*@
            @Html.ActionLink(item.Name, "Index", "Champ", new { champSeasonId = item.Id.ToString() }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Start)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.End)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MigrationId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>